spring:
  application:
    name: orders-service
  datasource:
    url: jdbc:postgresql://localhost:5434/orders
    username: order-service
    password: order-service-password
    hikari:
      idle-timeout: 300000
      connection-test-query: SELECT 1
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true
server:
  port: 8082
