version: "3.8"

services:

  postgresql:
    container_name: database
    image: postgres:15.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user-admin
    networks:
      - my_custom_network

networks:
  my_custom_network:
    name: user-service-network
    driver: bridge