INSERT INTO users (username, password, email, first_name, last_name)
VALUES ('charlie', 'hashed_password_5', 'charlie@example.com', 'Charlie', 'Brown'),
       ('david', 'hashed_password_6', 'david@example.com', 'David', 'Smith'),
       ('eve', 'hashed_password_7', 'eve@example.com', 'Eve', 'Davis'),
       ('frank', 'hashed_password_8', 'frank@example.com', 'Frank', 'Wilson'),
       ('grace', 'hashed_password_9', 'grace@example.com', 'Grace', 'Taylor'),
       ('henry', 'hashed_password_10', 'henry@example.com', 'Henry', 'Moore'),
       ('isla', 'hashed_password_11', 'isla@example.com', 'Isla', 'Anderson'),
       ('jack', 'hashed_password_12', 'jack@example.com', 'Jack', 'Thomas'),
       ('katie', 'hashed_password_13', 'katie@example.com', 'Katie', 'Jackson'),
       ('luke', 'hashed_password_14', 'luke@example.com', 'Luke', 'White'),
       ('mona', 'hashed_password_15', 'mona@example.com', 'Mona', 'Harris'),
       ('nora', 'hashed_password_16', 'nora@example.com', 'Nora', 'Martin'),
       ('oliver', 'hashed_password_17', 'oliver@example.com', 'Oliver', 'Thompson'),
       ('paul', 'hashed_password_18', 'paul@example.com', 'Paul', 'Garcia'),
       ('quinn', 'hashed_password_19', 'quinn@example.com', 'Quinn', 'Martinez'),
       ('rachel', 'hashed_password_20', 'rachel@example.com', 'Rachel', 'Robinson'),
       ('sophia', 'hashed_password_21', 'sophia@example.com', 'Sophia', 'Clark'),
       ('tina', 'hashed_password_22', 'tina@example.com', 'Tina', 'Rodriguez'),
       ('uma', 'hashed_password_23', 'uma@example.com', 'Uma', 'Lewis'),
       ('viktor', 'hashed_password_24', 'viktor@example.com', 'Viktor', 'Lee');
