spring:
  application:
    name: item-service
  datasource:
    url: jdbc:postgresql://localhost:5432/items
    username: item-service
    password: item-service-password
    hikari:
      idle-timeout: 300000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true
server:
  port: 8081
