version: '3.8'

services:

  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    environment:
      AMQ_USER: "admin"
      AMQ_PASSWORD: "admin"
      AMQ_EXTRA_ARGS: "--nio --relax-jolokia"
    networks:
      - amqp-quickstart-network
networks:
  amqp-quickstart-network: