spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jooq-demo
    password: qwerty123
    username: qwerty123
  flyway:
    validate-on-migrate: false
logging:
  level:
    org.jooq: debug
